apiVersion: v1
kind: Service
metadata:
  name: watching-pod
  namespace: default
spec:
  type: NodePort
  selector:
    app: watching-pod
  ports:
  - port: 9000
    targetPort: 8000
    nodePort: 30030
