apiVersion: apps/v1
kind: Deployment
metadata:
  name: watching-pod
  namespace: default
spec:
  selector:
    matchLabels:
      app: watching-pod
  template:
    metadata:
      labels:
        app: watching-pod
    spec:
      serviceAccountName: jsh
      automountServiceAccountToken: true
      containers:
      - name: app
        image: asdfry/watching-pod:20230629
        imagePullPolicy: Always
        ports:
        - name: app
          containerPort: 8000
      - name: db
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "ten"
        - name: MYSQL_USER
          value: "intstr"
        - name: MYSQL_PASSWORD
          value: "0604"
        ports:
        - name: db
          containerPort: 3306
