apiVersion: apps/v1
kind: Deployment
metadata:
  name: watching-pod
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      serviceAccountName: jsh
      automountServiceAccountToken: true
      containers:
      - name: app
        image: asdfry/watching-pod:20230625
        imagePullPolicy: Always
        ports:
        - name: app
          containerPort: 8000
      - name: db
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "ten"
        - name: MYSQL_USER
          value: "intstr"
        - name: MYSQL_PASSWORD
          value: "0604"
        ports:
        - name: db
          containerPort: 3306
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
